/* GENERATED by tools/market.py from markets/greece/*.json and islands/*.json.
   Edit the JSON and rebuild; changes made here are overwritten. */
const MARKET_KEY = "greece";
const ISLANDS_DATA = {
  "lefkada": {"name": "Lefkada", "lat": 38.7089, "lng": 20.6469, "beach": 4.9, "hist": 2.5, "night": 3.2, "access": 4.5, "afford": 4, "car_need": 4, "has_airport": true, "total": 4, "area": 335, "pop": 22600, "days": 4, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "arki": {"name": "Arki", "lat": 37.3861, "lng": 26.7345, "beach": 3, "hist": 1.5, "night": 1, "access": 1.5, "afford": 4.3, "car_need": 1, "has_airport": false, "total": 3, "area": 7, "pop": 44, "days": 1, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "othonoi": {"name": "Othonoi", "lat": 39.8539, "lng": 19.4018, "beach": 3.5, "hist": 2.5, "night": 1.5, "access": 1.5, "afford": 4.2, "car_need": 1, "has_airport": false, "total": 3.1, "area": 11, "pop": 457, "days": 1, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "mathraki": {"name": "Mathraki", "lat": 39.7689, "lng": 19.5239, "beach": 4, "hist": 1.5, "night": 1, "access": 1.5, "afford": 4.3, "car_need": 1, "has_airport": false, "total": 3.1, "area": 4, "pop": 330, "days": 1, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "pserimos": {"name": "Pserimos", "lat": 36.9421, "lng": 27.1416, "beach": 4, "hist": 1.5, "night": 1.5, "access": 2, "afford": 4, "car_need": 1, "has_airport": false, "total": 3.2, "area": 15, "pop": 84, "days": 1, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "telendos": {"name": "Telendos", "lat": 36.998, "lng": 26.918, "beach": 2.8, "hist": 3, "night": 1.5, "access": 2.5, "afford": 4, "car_need": 1, "has_airport": false, "total": 3.3, "area": 5, "pop": 50, "days": 1, "island_group": "Dodecanese", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "erikousa": {"name": "Erikousa", "lat": 39.888, "lng": 19.5802, "beach": 3.8, "hist": 2, "night": 1.5, "access": 2, "afford": 4.2, "car_need": 1, "has_airport": false, "total": 3.2, "area": 4, "pop": 447, "days": 1, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "kastos": {"name": "Kastos", "lat": 38.5726, "lng": 20.9128, "beach": 2.8, "hist": 2, "night": 1, "access": 1.5, "afford": 4, "car_need": 1, "has_airport": false, "total": 3, "area": 6, "pop": 40, "days": 1, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "kalamos": {"name": "Kalamos", "lat": 38.6235, "lng": 20.9088, "beach": 3, "hist": 2, "night": 1.3, "access": 2, "afford": 4.2, "car_need": 1, "has_airport": false, "total": 3.2, "area": 25, "pop": 496, "days": 1, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "thymaina": {"name": "Thymaina", "lat": 37.5835, "lng": 26.4338, "beach": 2.8, "hist": 1.5, "night": 1, "access": 1.5, "afford": 4.3, "car_need": 1, "has_airport": false, "total": 3, "area": 10, "pop": 191, "days": 1, "island_group": "NE Aegean", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "meganisi": {"name": "Meganisi", "lat": 38.6473, "lng": 20.7701, "beach": 4, "hist": 2.5, "night": 2.8, "access": 3.2, "afford": 3.2, "car_need": 2.5, "has_airport": false, "total": 3.5, "area": 22, "pop": 1041, "days": 2, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "ithaca": {"name": "Ithaca", "lat": 38.4032, "lng": 20.6865, "beach": 3.8, "hist": 4.9, "night": 2.5, "access": 2.5, "afford": 3.5, "car_need": 3.5, "has_airport": false, "total": 3.8, "area": 96, "pop": 3231, "days": 3, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "kefalonia": {"name": "Kefalonia", "lat": 38.2266, "lng": 20.5749, "beach": 4.7, "hist": 3.2, "night": 3.2, "access": 3.5, "afford": 3.8, "car_need": 5, "has_airport": true, "total": 4.1, "area": 773, "pop": 35800, "days": 5, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "zakynthos": {"name": "Zakynthos", "lat": 37.7875, "lng": 20.7748, "beach": 4.8, "hist": 2.5, "night": 4.5, "access": 3.7, "afford": 3.5, "car_need": 4, "has_airport": true, "total": 4.1, "area": 405, "pop": 40700, "days": 4, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "kythira": {"name": "Kythira", "lat": 36.2529, "lng": 22.9847, "beach": 4.2, "hist": 4.5, "night": 2.5, "access": 2.5, "afford": 3.8, "car_need": 5, "has_airport": true, "total": 3.8, "area": 279, "pop": 3973, "days": 4, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "antikythera": {"name": "Antikythera", "lat": 35.8651, "lng": 23.3083, "beach": 3.5, "hist": 4.5, "night": 1, "access": 1, "afford": 3.5, "car_need": 1.5, "has_airport": false, "total": 3, "area": 20, "pop": 40, "days": 1, "island_group": "Ionian", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "elafonisos": {"name": "Elafonisos", "lat": 36.4854, "lng": 22.96, "beach": 5, "hist": 2, "night": 2.5, "access": 2.5, "afford": 3.8, "car_need": 1, "has_airport": false, "total": 4, "area": 19, "pop": 1041, "days": 2, "island_group": "Other", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "paros": {"name": "Paros", "lat": 37.0625, "lng": 25.1959, "beach": 5, "hist": 3.8, "night": 5, "access": 4.5, "afford": 2.2, "car_need": 3, "has_airport": true, "total": 4.1, "area": 196, "pop": 13700, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "chania": {"name": "Crete (Chania)", "lat": 35.32, "lng": 23.9, "beach": 5, "hist": 4.7, "night": 4, "access": 4.5, "afford": 3.4, "car_need": 5, "has_airport": true, "total": 4.8, "area": 2376, "pop": 108000, "days": 5, "island_group": "Crete", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "heraklion": {"name": "Crete (Heraklion)", "lat": 35.15, "lng": 25.1, "beach": 3.5, "hist": 5, "night": 4.7, "access": 5, "afford": 3.5, "car_need": 5, "has_airport": true, "total": 4.2, "area": 2641, "pop": 173000, "days": 5, "island_group": "Crete", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "rethymno": {"name": "Crete (Rethymno)", "lat": 35.25, "lng": 24.55, "beach": 3.8, "hist": 4.5, "night": 3.8, "access": 3.5, "afford": 3.7, "car_need": 5, "has_airport": false, "total": 3.8, "area": 1496, "pop": 34300, "days": 4, "island_group": "Crete", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "lasithi": {"name": "Crete (Lasithi)", "lat": 35.15, "lng": 25.9, "beach": 4, "hist": 3.5, "night": 3.4, "access": 3.2, "afford": 3.2, "car_need": 5, "has_airport": true, "total": 4, "area": 1823, "pop": 76000, "days": 4, "island_group": "Crete", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "santorini": {"name": "Santorini", "lat": 36.3975, "lng": 25.4403, "beach": 3.2, "hist": 5, "night": 4.2, "access": 4.7, "afford": 1, "car_need": 3, "has_airport": true, "total": 4.8, "area": 76, "pop": 15500, "days": 3, "island_group": "Cyclades", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "milos": {"name": "Milos", "lat": 36.7193, "lng": 24.5064, "beach": 5, "hist": 3.5, "night": 3, "access": 3.2, "afford": 2.8, "car_need": 4, "has_airport": true, "total": 4.7, "area": 151, "pop": 4900, "days": 4, "island_group": "Cyclades", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "rhodes": {"name": "Rhodes", "lat": 36.1863, "lng": 27.9505, "beach": 4.2, "hist": 5, "night": 4.1, "access": 4.8, "afford": 3.5, "car_need": 5, "has_airport": true, "total": 4.4, "area": 1400, "pop": 115000, "days": 5, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": true},
  "naxos": {"name": "Naxos", "lat": 37.0622, "lng": 25.4883, "beach": 4.8, "hist": 4.4, "night": 3.5, "access": 3.8, "afford": 4, "car_need": 4, "has_airport": true, "total": 4.5, "area": 429, "pop": 18900, "days": 4, "island_group": "Cyclades", "drama": false, "hiking": true, "springs": false, "chora": true, "sailing": true},
  "mykonos": {"name": "Mykonos", "lat": 37.4562, "lng": 25.3764, "beach": 4.3, "hist": 3, "night": 5, "access": 4.8, "afford": 1, "car_need": 3, "has_airport": true, "total": 4.3, "area": 85, "pop": 10100, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "corfu": {"name": "Corfu", "lat": 39.6393, "lng": 19.8453, "beach": 3.9, "hist": 4.8, "night": 4.2, "access": 4.7, "afford": 3.2, "car_need": 4, "has_airport": true, "total": 4.2, "area": 593, "pop": 102000, "days": 5, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "hydra": {"name": "Hydra", "lat": 37.3379, "lng": 23.474, "beach": 2.2, "hist": 4.2, "night": 3.8, "access": 4.2, "afford": 1.8, "car_need": 1, "has_airport": false, "total": 4, "area": 52, "pop": 2700, "days": 2, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "folegandros": {"name": "Folegandros", "lat": 36.6313, "lng": 24.9044, "beach": 3.9, "hist": 3.8, "night": 3.5, "access": 2.8, "afford": 2.2, "car_need": 3, "has_airport": false, "total": 4, "area": 32, "pop": 765, "days": 3, "island_group": "Cyclades", "drama": true, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "koufonisia": {"name": "Koufonisia", "lat": 36.945, "lng": 25.6, "beach": 5, "hist": 2, "night": 4, "access": 3, "afford": 3, "car_need": 1, "has_airport": false, "total": 4, "area": 26, "pop": 399, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "evia-north": {"name": "Evia (North)", "lat": 38.85, "lng": 23.2, "beach": 3.8, "hist": 3.5, "night": 2.5, "access": 4.5, "afford": 4.8, "car_need": 5, "has_airport": false, "total": 3.6, "area": 1200, "pop": 48000, "days": 3, "island_group": "Evia", "drama": false, "hiking": true, "springs": true, "chora": false, "sailing": false},
  "evia-central": {"name": "Evia (Central)", "lat": 38.5, "lng": 23.85, "beach": 3.5, "hist": 4.5, "night": 3.5, "access": 5, "afford": 4.6, "car_need": 5, "has_airport": false, "total": 3.9, "area": 1700, "pop": 120000, "days": 3, "island_group": "Evia", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "evia-south": {"name": "Evia (South)", "lat": 38.016, "lng": 24.42, "beach": 4.6, "hist": 3.5, "night": 2.5, "access": 4.5, "afford": 4.5, "car_need": 5, "has_airport": false, "total": 3.9, "area": 780, "pop": 42000, "days": 3, "island_group": "Evia", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "lesvos": {"name": "Lesvos", "lat": 39.21, "lng": 26.21, "beach": 4, "hist": 4.7, "night": 3, "access": 3.5, "afford": 4.6, "car_need": 5, "has_airport": true, "total": 4, "area": 1633, "pop": 83000, "days": 6, "island_group": "NE Aegean", "drama": false, "hiking": true, "springs": true, "chora": true, "sailing": false},
  "chios": {"name": "Chios", "lat": 38.4039, "lng": 26.0159, "beach": 3.2, "hist": 4.7, "night": 2.5, "access": 3.2, "afford": 4.5, "car_need": 4, "has_airport": true, "total": 3.6, "area": 842, "pop": 51000, "days": 4, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "kos": {"name": "Kos", "lat": 36.8183, "lng": 27.1305, "beach": 4, "hist": 4.2, "night": 4, "access": 4.6, "afford": 3.8, "car_need": 4, "has_airport": true, "total": 3.7, "area": 287, "pop": 33300, "days": 4, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "samos": {"name": "Samos", "lat": 37.7356, "lng": 26.8142, "beach": 3.5, "hist": 4.6, "night": 3, "access": 3.5, "afford": 4.2, "car_need": 4, "has_airport": true, "total": 3.3, "area": 477, "pop": 32900, "days": 4, "island_group": "NE Aegean", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "syros": {"name": "Syros", "lat": 37.4357, "lng": 24.9179, "beach": 2.8, "hist": 4.3, "night": 3.5, "access": 4.5, "afford": 3.5, "car_need": 3, "has_airport": true, "total": 3.8, "area": 84, "pop": 21500, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "lemnos": {"name": "Lemnos", "lat": 39.9217, "lng": 25.2253, "beach": 4.3, "hist": 3.5, "night": 2.2, "access": 3, "afford": 4.4, "car_need": 4, "has_airport": true, "total": 3.7, "area": 477, "pop": 16900, "days": 3, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "agios-efstratios": {"name": "Agios Efstratios", "lat": 39.5208, "lng": 25.0062, "beach": 4.5, "hist": 2.8, "night": 1.5, "access": 1.5, "afford": 4.5, "car_need": 1, "has_airport": false, "total": 3.3, "area": 43, "pop": 270, "days": 1, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "psara": {"name": "Psara", "lat": 38.55, "lng": 25.54, "beach": 3.8, "hist": 3.5, "night": 1.5, "access": 1.5, "afford": 4.2, "car_need": 1, "has_airport": false, "total": 3, "area": 40, "pop": 450, "days": 1, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "oinousses": {"name": "Oinousses", "lat": 38.5221, "lng": 26.2266, "beach": 3.5, "hist": 3.2, "night": 1.8, "access": 2, "afford": 4, "car_need": 1, "has_airport": false, "total": 3, "area": 14, "pop": 820, "days": 1, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "iraklia": {"name": "Iraklia", "lat": 36.8435, "lng": 25.4548, "beach": 4.2, "hist": 2.5, "night": 1.5, "access": 2, "afford": 4.3, "car_need": 1, "has_airport": false, "total": 3.2, "area": 18, "pop": 140, "days": 1, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "kalymnos": {"name": "Kalymnos", "lat": 36.9931, "lng": 26.9715, "beach": 3.5, "hist": 4, "night": 3, "access": 3.2, "afford": 4.2, "car_need": 4, "has_airport": true, "total": 3.5, "area": 110, "pop": 16179, "days": 3, "island_group": "Dodecanese", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "thasos": {"name": "Thasos", "lat": 40.6896, "lng": 24.6549, "beach": 4.2, "hist": 3.2, "night": 3, "access": 3.2, "afford": 4.1, "car_need": 4, "has_airport": false, "total": 3.7, "area": 379, "pop": 13700, "days": 3, "island_group": "Other", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "aegina": {"name": "Aegina", "lat": 37.7357, "lng": 23.4929, "beach": 2.5, "hist": 4.2, "night": 3.2, "access": 5, "afford": 3.5, "car_need": 3, "has_airport": false, "total": 3.3, "area": 87, "pop": 13000, "days": 1, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "tinos": {"name": "Tinos", "lat": 37.6089, "lng": 25.1329, "beach": 3.5, "hist": 4, "night": 3, "access": 4.2, "afford": 3.2, "car_need": 4, "has_airport": false, "total": 3.7, "area": 194, "pop": 8600, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "andros": {"name": "Andros", "lat": 37.8617, "lng": 24.8511, "beach": 3.8, "hist": 4, "night": 2.8, "access": 4, "afford": 3.2, "car_need": 4, "has_airport": false, "total": 3.7, "area": 380, "pop": 9200, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": true, "springs": false, "chora": true, "sailing": false},
  "ikaria": {"name": "Ikaria", "lat": 37.5971, "lng": 26.1502, "beach": 4, "hist": 3, "night": 4.5, "access": 2.5, "afford": 4.5, "car_need": 4, "has_airport": true, "total": 3.8, "area": 255, "pop": 8400, "days": 4, "island_group": "NE Aegean", "drama": true, "hiking": true, "springs": true, "chora": false, "sailing": false},
  "leros": {"name": "Leros", "lat": 37.1505, "lng": 26.8324, "beach": 3.2, "hist": 4, "night": 3, "access": 3.2, "afford": 4.2, "car_need": 3, "has_airport": true, "total": 3.3, "area": 53, "pop": 7900, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "karpathos": {"name": "Karpathos", "lat": 35.5969, "lng": 27.1574, "beach": 4.4, "hist": 4, "night": 2.2, "access": 2, "afford": 3.8, "car_need": 5, "has_airport": true, "total": 3.8, "area": 300, "pop": 6200, "days": 4, "island_group": "Dodecanese", "drama": true, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "skiathos": {"name": "Skiathos", "lat": 39.1734, "lng": 23.4588, "beach": 4.6, "hist": 2, "night": 4.7, "access": 4.5, "afford": 3, "car_need": 3, "has_airport": true, "total": 3.9, "area": 49, "pop": 6088, "days": 3, "island_group": "Sporades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "skopelos": {"name": "Skopelos", "lat": 39.1326, "lng": 23.6907, "beach": 4.2, "hist": 3.2, "night": 2.5, "access": 2.5, "afford": 3.8, "car_need": 4, "has_airport": false, "total": 3.6, "area": 96, "pop": 4960, "days": 3, "island_group": "Sporades", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "patmos": {"name": "Patmos", "lat": 37.3318, "lng": 26.5575, "beach": 3, "hist": 4.8, "night": 2.8, "access": 2.2, "afford": 2.5, "car_need": 3, "has_airport": false, "total": 3.6, "area": 34, "pop": 3047, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "poros": {"name": "Poros", "lat": 37.5256, "lng": 23.4806, "beach": 3, "hist": 4.2, "night": 3.5, "access": 4.8, "afford": 3.2, "car_need": 3, "has_airport": false, "total": 3.5, "area": 23, "pop": 3993, "days": 1, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "alonnisos": {"name": "Alonnisos", "lat": 39.2129, "lng": 23.9114, "beach": 4.4, "hist": 3, "night": 2.5, "access": 2.5, "afford": 4, "car_need": 3, "has_airport": false, "total": 3.8, "area": 64, "pop": 2750, "days": 3, "island_group": "Sporades", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": true},
  "skyros": {"name": "Skyros", "lat": 38.8703, "lng": 24.5532, "beach": 4, "hist": 3.8, "night": 2.8, "access": 2.5, "afford": 4.2, "car_need": 4, "has_airport": true, "total": 3.4, "area": 209, "pop": 2994, "days": 3, "island_group": "Sporades", "drama": true, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "sifnos": {"name": "Sifnos", "lat": 36.9779, "lng": 24.7069, "beach": 3.8, "hist": 4, "night": 3.2, "access": 3.5, "afford": 3.5, "car_need": 4, "has_airport": false, "total": 3.9, "area": 73, "pop": 2625, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "symi": {"name": "Symi", "lat": 36.5853, "lng": 27.8309, "beach": 3, "hist": 4.8, "night": 3.5, "access": 3.5, "afford": 2.5, "car_need": 2, "has_airport": false, "total": 3.8, "area": 58, "pop": 2590, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "paxos": {"name": "Paxos", "lat": 39.2079, "lng": 20.1616, "beach": 4.2, "hist": 3, "night": 3.5, "access": 2.8, "afford": 2.5, "car_need": 2, "has_airport": false, "total": 4, "area": 19, "pop": 2300, "days": 2, "island_group": "Ionian", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "kea": {"name": "Kea (Tzia)", "lat": 37.6144, "lng": 24.3315, "beach": 3.8, "hist": 3.8, "night": 3, "access": 4.5, "afford": 3, "car_need": 4, "has_airport": false, "total": 3.5, "area": 131, "pop": 2455, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "ios": {"name": "Ios", "lat": 36.7227, "lng": 25.3301, "beach": 4.6, "hist": 2.5, "night": 5, "access": 3.2, "afford": 3.5, "car_need": 3, "has_airport": false, "total": 3.9, "area": 109, "pop": 2024, "days": 3, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "amorgos": {"name": "Amorgos", "lat": 36.8482, "lng": 25.9046, "beach": 4, "hist": 3.8, "night": 3.5, "access": 2.5, "afford": 3.5, "car_need": 4, "has_airport": false, "total": 4, "area": 126, "pop": 1973, "days": 4, "island_group": "Cyclades", "drama": true, "hiking": true, "springs": false, "chora": true, "sailing": false},
  "kythnos": {"name": "Kythnos", "lat": 37.3975, "lng": 24.4193, "beach": 4.2, "hist": 3.2, "night": 3, "access": 3.5, "afford": 3.8, "car_need": 3, "has_airport": false, "total": 3.5, "area": 100, "pop": 1456, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": true, "chora": false, "sailing": false},
  "astypalaia": {"name": "Astypalaia", "lat": 36.5722, "lng": 26.3503, "beach": 4, "hist": 4.2, "night": 3, "access": 2.5, "afford": 3.8, "car_need": 4, "has_airport": true, "total": 3.8, "area": 97, "pop": 1334, "days": 3, "island_group": "Dodecanese", "drama": true, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "antiparos": {"name": "Antiparos", "lat": 37.0035, "lng": 25.0563, "beach": 4.5, "hist": 3, "night": 4, "access": 3.5, "afford": 2.8, "car_need": 3, "has_airport": false, "total": 4, "area": 35, "pop": 1211, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "serifos": {"name": "Serifos", "lat": 37.1624, "lng": 24.4835, "beach": 4.5, "hist": 3.2, "night": 3, "access": 3.5, "afford": 3.8, "car_need": 2.5, "has_airport": false, "total": 3.9, "area": 75, "pop": 1420, "days": 3, "island_group": "Cyclades", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "agistri": {"name": "Agistri", "lat": 37.7, "lng": 23.35, "beach": 3.5, "hist": 2.5, "night": 3.5, "access": 4.5, "afford": 4, "car_need": 1, "has_airport": false, "total": 3.4, "area": 13, "pop": 1142, "days": 1, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "nisyros": {"name": "Nisyros", "lat": 36.5862, "lng": 27.167, "beach": 3, "hist": 5, "night": 2.5, "access": 2.8, "afford": 4, "car_need": 3, "has_airport": false, "total": 3.8, "area": 41, "pop": 1008, "days": 1, "island_group": "Dodecanese", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "kimolos": {"name": "Kimolos", "lat": 36.815, "lng": 24.5615, "beach": 4.5, "hist": 3.2, "night": 2.5, "access": 3, "afford": 3.8, "car_need": 3, "has_airport": false, "total": 3.6, "area": 36, "pop": 910, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "kastellorizo": {"name": "Kastellorizo", "lat": 36.1436, "lng": 29.5809, "beach": 2, "hist": 5, "night": 2.8, "access": 1.2, "afford": 3.5, "car_need": 1, "has_airport": true, "total": 4, "area": 12, "pop": 492, "days": 1, "island_group": "Dodecanese", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "sikinos": {"name": "Sikinos", "lat": 36.682, "lng": 25.1254, "beach": 3.5, "hist": 4.2, "night": 2.2, "access": 2.5, "afford": 4, "car_need": 3, "has_airport": false, "total": 3.4, "area": 42, "pop": 273, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "anafi": {"name": "Anafi", "lat": 36.3737, "lng": 25.7832, "beach": 4.5, "hist": 3.2, "night": 2.5, "access": 2, "afford": 4.2, "car_need": 3, "has_airport": false, "total": 3.9, "area": 38, "pop": 271, "days": 2, "island_group": "Cyclades", "drama": true, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "samothrace": {"name": "Samothrace", "lat": 40.459, "lng": 25.5809, "beach": 3, "hist": 4.1, "night": 2.5, "access": 1.8, "afford": 4.5, "car_need": 3, "has_airport": false, "total": 3.2, "area": 178, "pop": 2859, "days": 3, "island_group": "Other", "drama": true, "hiking": true, "springs": true, "chora": false, "sailing": false},
  "fournoi": {"name": "Fournoi", "lat": 37.5942, "lng": 26.5054, "beach": 3.8, "hist": 3, "night": 1.8, "access": 2, "afford": 4.5, "car_need": 3, "has_airport": false, "total": 3.2, "area": 45, "pop": 1459, "days": 2, "island_group": "NE Aegean", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "spetses": {"name": "Spetses", "lat": 37.2648, "lng": 23.1336, "beach": 2.8, "hist": 3.9, "night": 4.2, "access": 3.9, "afford": 2, "car_need": 2, "has_airport": false, "total": 3.7, "area": 22, "pop": 4027, "days": 2, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": true},
  "tilos": {"name": "Tilos", "lat": 36.428, "lng": 27.3629, "beach": 3.8, "hist": 3.5, "night": 2, "access": 2.2, "afford": 4.2, "car_need": 3, "has_airport": false, "total": 3.5, "area": 61, "pop": 746, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": true, "springs": false, "chora": false, "sailing": false},
  "leipsoi": {"name": "Leipsoi", "lat": 37.3021, "lng": 26.7533, "beach": 4, "hist": 3, "night": 2, "access": 2.5, "afford": 4.5, "car_need": 2, "has_airport": false, "total": 3.4, "area": 16, "pop": 790, "days": 1, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "halki": {"name": "Halki", "lat": 36.2291, "lng": 27.5683, "beach": 3.8, "hist": 4, "night": 2, "access": 2.5, "afford": 4, "car_need": 2, "has_airport": false, "total": 3.6, "area": 28, "pop": 478, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": true, "sailing": false},
  "ammouliani": {"name": "Ammouliani", "lat": 40.3271, "lng": 23.9099, "beach": 4.5, "hist": 2, "night": 3, "access": 3, "afford": 4, "car_need": 1, "has_airport": false, "total": 3.5, "area": 4, "pop": 547, "days": 2, "island_group": "Other", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "salamis": {"name": "Salamis", "lat": 37.9404, "lng": 23.4823, "beach": 2, "hist": 3.5, "night": 3, "access": 4.5, "afford": 4.5, "car_need": 3, "has_airport": false, "total": 2.8, "area": 95, "pop": 39283, "days": 1, "island_group": "Saronic", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "therasia": {"name": "Therasia", "lat": 36.445, "lng": 25.335, "beach": 3, "hist": 3.5, "night": 1.5, "access": 3, "afford": 3.5, "car_need": 1, "has_airport": false, "total": 3.1, "area": 9, "pop": 319, "days": 1, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "schoinoussa": {"name": "Schoinoussa", "lat": 36.87, "lng": 25.51, "beach": 4.5, "hist": 2, "night": 2.5, "access": 2.5, "afford": 3.8, "car_need": 1, "has_airport": false, "total": 3.4, "area": 8, "pop": 227, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "donousa": {"name": "Donousa", "lat": 37.114, "lng": 25.8141, "beach": 4.5, "hist": 2, "night": 2.5, "access": 2.2, "afford": 3.8, "car_need": 1, "has_airport": false, "total": 3.4, "area": 13, "pop": 167, "days": 2, "island_group": "Cyclades", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "kasos": {"name": "Kasos", "lat": 35.3964, "lng": 26.928, "beach": 3.2, "hist": 3.8, "night": 1.5, "access": 1.5, "afford": 4.5, "car_need": 3, "has_airport": true, "total": 2.8, "area": 66, "pop": 1084, "days": 2, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "agathonisi": {"name": "Agathonisi", "lat": 37.462, "lng": 26.9676, "beach": 3.5, "hist": 2, "night": 1.5, "access": 1.8, "afford": 4.5, "car_need": 1, "has_airport": false, "total": 3, "area": 13, "pop": 185, "days": 1, "island_group": "Dodecanese", "drama": false, "hiking": false, "springs": false, "chora": false, "sailing": false},
  "gavdos": {"name": "Gavdos", "lat": 34.8444, "lng": 24.0959, "beach": 4.8, "hist": 2, "night": 2.5, "access": 1, "afford": 4.5, "car_need": 1, "has_airport": false, "total": 3, "area": 33, "pop": 152, "days": 3, "island_group": "Crete", "drama": true, "hiking": false, "springs": false, "chora": false, "sailing": false}
};
const ISLAND_CLUSTERS = {
  "diapontia": {
    "name": "the Diapontia islands",
    "name_el": "τα Διαπόντια νησιά",
    "members": [
      "othonoi",
      "erikousa",
      "mathraki"
    ],
    "gateway": "corfu",
    "score": 4,
    "days": 4,
    "why": "One boat out of Corfu, three islands, almost no other visitors — the access penalty that drags each island down on its own disappears once you treat them as a single trip.",
    "why_el": "Ένα καράβι από την Κέρκυρα, τρία νησιά, σχεδόν κανένας άλλος επισκέπτης — η δυσκολία πρόσβασης που ρίχνει τη βαθμολογία κάθε νησιού χωριστά εξαφανίζεται όταν τα δεις ως ένα ταξίδι.",
    "name_el_gen": "των Διαποντίων νησιών",
    "roles": {
      "othonoi": {
        "en": "The biggest and furthest out — Calypso's cave and the best walking of the three. Usually paired with a night on Erikousa.",
        "el": "Το μεγαλύτερο και πιο απομακρυσμένο — η σπηλιά της Καλυψώς και οι καλύτερες πεζοπορίες των τριών. Συνήθως συνδυάζεται με μια νύχτα στην Ερείκουσα."
      },
      "erikousa": {
        "en": "The easy one, and the only one with real sand. Day-trip it from Corfu, or sleep here between Othonoi and Mathraki.",
        "el": "Το εύκολο, και το μόνο με πραγματική αμμουδιά. Ημερήσια εκδρομή από την Κέρκυρα, ή διανυκτέρευση ανάμεσα σε Οθωνούς και Μαθράκι."
      },
      "mathraki": {
        "en": "The smallest and quietest — one long beach, 330 people. Most routes give it the half-day between Othonoi and Erikousa.",
        "el": "Το μικρότερο και πιο ήσυχο — μια μεγάλη παραλία, 330 κάτοικοι. Οι περισσότερες διαδρομές του δίνουν το μισό της μέρας ανάμεσα σε Οθωνούς και Ερείκουσα."
      }
    }
  },
  "inner-ionian": {
    "name": "the Inner Ionian",
    "name_el": "το Εσωτερικό Ιόνιο",
    "members": [
      "kastos",
      "kalamos",
      "meganisi"
    ],
    "gateway": "lefkada",
    "score": 4.1,
    "days": 4,
    "why": "These are hopping islands, not destinations. Based in Lefkada with a boat or the local ferries, the three of them together make one of the best low-key weeks in Greece.",
    "why_el": "Είναι νησιά για νησοπορία, όχι προορισμοί. Με βάση τη Λευκάδα και βάρκα ή τα τοπικά πλοία, τα τρία μαζί δίνουν μια από τις καλύτερες χαλαρές εβδομάδες στην Ελλάδα.",
    "name_el_gen": "του Εσωτερικού Ιονίου",
    "roles": {
      "kastos": {
        "en": "The quietest link in the chain — one village, no cars, a stone path. Most people stop here between Kalamos and Meganisi.",
        "el": "Ο πιο ήσυχος κρίκος της αλυσίδας — ένα χωριό, χωρίς αυτοκίνητα, ένα λιθόστρωτο μονοπάτι. Οι περισσότεροι σταματούν εδώ ανάμεσα σε Κάλαμο και Μεγανήσι."
      },
      "kalamos": {
        "en": "The green one, with the best anchorages and the Porto Leone ghost village. The natural middle stop between Meganisi and Kastos.",
        "el": "Το πράσινο, με τα καλύτερα αγκυροβόλια και το εγκαταλελειμμένο Πόρτο Λεόνε. Η φυσική ενδιάμεση στάση ανάμεσα σε Μεγανήσι και Καστό."
      },
      "meganisi": {
        "en": "The busiest and best-connected — twenty minutes from Lefkada, so most routes start or finish here before Kalamos and Kastos.",
        "el": "Το πιο ζωντανό και καλοσυνδεδεμένο — είκοσι λεπτά από τη Λευκάδα, οπότε οι περισσότερες διαδρομές ξεκινούν ή τελειώνουν εδώ, πριν από Κάλαμο και Καστό."
      }
    }
  },
  "kalymnos-satellites": {
    "name": "the Kalymnos satellites",
    "name_el": "οι δορυφόροι της Καλύμνου",
    "members": [
      "telendos",
      "pserimos"
    ],
    "gateway": "kalymnos",
    "score": 3.9,
    "days": 3,
    "why": "Both are short boat rides from Kalymnos and neither fills a day on its own. Paired with a Kalymnos base they turn into two excellent half-days.",
    "why_el": "Και τα δύο είναι λίγα λεπτά με βάρκα από την Κάλυμνο και κανένα δεν γεμίζει μέρα μόνο του. Με βάση την Κάλυμνο γίνονται δύο εξαιρετικά μισά της μέρας.",
    "name_el_gen": "των δορυφόρων της Καλύμνου",
    "roles": {
      "telendos": {
        "en": "Five minutes across the strait from Kalymnos — climbing, sunsets, waterfront tavernas. The evening half of the pair with Pserimos.",
        "el": "Πέντε λεπτά απέναντι από την Κάλυμνο — αναρρίχηση, ηλιοβασιλέματα, ταβέρνες στο κύμα. Το απογευματινό μισό του ζευγαριού με την Ψέριμο."
      },
      "pserimos": {
        "en": "One wide sandy bay between Kalymnos and Kos, and 84 residents. The beach half of the pair with Telendos.",
        "el": "Ένας πλατύς αμμώδης κόλπος ανάμεσα σε Κάλυμνο και Κω, και 84 κάτοικοι. Το «παραλιακό» μισό του ζευγαριού με την Τέλενδο."
      }
    }
  },
  "patmos-satellites": {
    "name": "the Patmos & Lipsi group",
    "name_el": "η ομάδα Πάτμου & Λειψών",
    "members": [
      "arki",
      "leipsoi",
      "agathonisi"
    ],
    "gateway": "patmos",
    "score": 3.9,
    "days": 4,
    "why": "Tiny, sleepy and connected by the same local boats. Strung together off Patmos they add up to a proper slow-travel week; visited singly they are half-day stops.",
    "why_el": "Μικροσκοπικά, νυσταγμένα και συνδεδεμένα με τα ίδια τοπικά καράβια. Στη σειρά από την Πάτμο δίνουν μια πραγματική εβδομάδα αργού ταξιδιού· χωριστά είναι στάσεις μισής μέρας.",
    "name_el_gen": "της ομάδας Πάτμου & Λειψών",
    "roles": {
      "arki": {
        "en": "The emptiest of the group — 44 residents and no cars. Reached on the same local boat line as Lipsi and Agathonisi.",
        "el": "Το πιο άδειο της ομάδας — 44 κάτοικοι και χωρίς αυτοκίνητα. Προσεγγίζεται με την ίδια τοπική γραμμή με Λειψούς και Αγαθονήσι."
      },
      "leipsoi": {
        "en": "The hub of the small ones — most of the rooms and tavernas, and the boat you take onward to Arki.",
        "el": "Ο κόμβος των μικρών — τα περισσότερα δωμάτια και ταβέρνες, και το καΐκι για τους Αρκιούς."
      },
      "agathonisi": {
        "en": "The furthest out, on the Samos line — usually the last stop after Lipsi and Arki, or the way you leave the group.",
        "el": "Το πιο απομακρυσμένο, στη γραμμή της Σάμου — συνήθως η τελευταία στάση μετά τους Λειψούς και τους Αρκιούς, ή ο τρόπος να φύγεις."
      }
    }
  },
  "fourni-group": {
    "name": "the Fournoi group",
    "name_el": "το σύμπλεγμα Φούρνων",
    "members": [
      "fournoi",
      "thymaina"
    ],
    "gateway": "ikaria",
    "score": 3.9,
    "days": 3,
    "why": "Thymaina only makes sense as part of Fournoi, and Fournoi makes most sense as an add-on to Ikaria or Samos. Together it is one of the least-visited corners of the Aegean.",
    "why_el": "Η Θύμαινα βγάζει νόημα μόνο μαζί με τους Φούρνους, και οι Φούρνοι κυρίως ως προέκταση της Ικαρίας ή της Σάμου. Μαζί είναι μια από τις γωνιές με τους λιγότερους επισκέπτες του Αιγαίου.",
    "name_el_gen": "του συμπλέγματος Φούρνων",
    "roles": {
      "fournoi": {
        "en": "The main island of the pair — harbour, tavernas, and a coastline of small beaches. Thymaina sits across the strait.",
        "el": "Το κύριο νησί του ζευγαριού — λιμάνι, ταβέρνες και μια ακτογραμμή με μικρές παραλίες. Η Θύμαινα είναι απέναντι."
      },
      "thymaina": {
        "en": "Fournoi's little sibling — a fishing village and very little else, and you can only get here through Fournoi.",
        "el": "Η μικρή αδελφή των Φούρνων — ένα ψαροχώρι και ελάχιστα άλλα, και φτάνεις μόνο μέσω Φούρνων."
      }
    }
  }
};
const HOMEPAGE_FEATURED = [
  {
    "key": "folegandros",
    "tagEn": "Quiet escape",
    "tagEl": "Ήσυχη απόδραση"
  },
  {
    "key": "milos",
    "tagEn": "Beach trip",
    "tagEl": "Παραλιακή απόδραση"
  },
  {
    "key": "santorini",
    "tagEn": "Iconic",
    "tagEl": "Εμβληματική"
  },
  {
    "key": "hydra",
    "tagEn": "No cars",
    "tagEl": "Χωρίς αυτοκίνητα"
  },
  {
    "key": "symi",
    "tagEn": "Off-radar",
    "tagEl": "Εκτός ραντάρ"
  },
  {
    "key": "naxos",
    "tagEn": "Family-friendly",
    "tagEl": "Φιλικό για οικογένειες"
  }
];
const HOME_HERO_KEYS = ["kythira", "milos", "folegandros", "naxos", "skopelos"];
const WTV_TAGS = {
  "aegina": [2, 1, 2, 2, 3, 3, 1, 0, 3, 2, 2, 2],
  "agathonisi": [0, 0, 0, 0, 1, 3, 2, 1, 3, 0, 0, 0],
  "agios-efstratios": [0, 0, 0, 0, 1, 3, 2, 1, 3, 0, 0, 0],
  "agistri": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 1, 1],
  "alonnisos": [0, 0, 1, 2, 3, 3, 2, 1, 3, 2, 1, 0],
  "ammouliani": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 0, 0],
  "amorgos": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 1, 0],
  "anafi": [0, 0, 0, 1, 1, 3, 2, 1, 3, 1, 0, 0],
  "andros": [1, 1, 2, 2, 3, 3, 1, 0, 3, 2, 1, 1],
  "antikythera": [0, 0, 0, 0, 1, 3, 2, 1, 3, 0, 0, 0],
  "antiparos": [0, 0, 1, 2, 3, 3, 2, 1, 3, 2, 1, 0],
  "arki": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "astypalaia": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 0, 0],
  "chania": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "chios": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "corfu": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "donousa": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "elafonisos": [0, 0, 1, 2, 3, 3, 1, 0, 3, 2, 0, 0],
  "erikousa": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "evia-central": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 1],
  "evia-north": [2, 2, 2, 2, 2, 3, 1, 1, 3, 2, 2, 2],
  "evia-south": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 1],
  "folegandros": [0, 0, 1, 2, 3, 3, 2, 1, 3, 2, 1, 0],
  "fournoi": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 0, 0],
  "gavdos": [0, 0, 0, 1, 2, 3, 1, 0, 3, 1, 0, 0],
  "halki": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 0, 0],
  "heraklion": [1, 1, 2, 2, 2, 3, 1, 1, 3, 2, 2, 1],
  "hydra": [1, 1, 2, 2, 3, 3, 1, 0, 3, 2, 2, 1],
  "ikaria": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "ios": [0, 0, 1, 1, 2, 2, 3, 3, 3, 2, 1, 0],
  "iraklia": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "ithaca": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "kalamos": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "kalymnos": [2, 2, 3, 2, 2, 3, 1, 0, 3, 3, 2, 2],
  "karpathos": [0, 0, 1, 2, 2, 3, 2, 1, 3, 3, 1, 0],
  "kasos": [0, 0, 0, 1, 1, 3, 2, 1, 3, 0, 0, 0],
  "kastellorizo": [0, 0, 1, 2, 2, 3, 2, 0, 3, 2, 0, 0],
  "kastos": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "kea": [1, 1, 2, 2, 3, 2, 1, 1, 3, 2, 1, 1],
  "kefalonia": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "kimolos": [0, 0, 1, 2, 2, 3, 1, 1, 3, 2, 0, 0],
  "kos": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "koufonisia": [0, 0, 0, 1, 2, 3, 2, 1, 3, 2, 0, 0],
  "kythira": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "kythnos": [1, 1, 2, 2, 3, 3, 1, 0, 3, 2, 1, 1],
  "lasithi": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "lefkada": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 1],
  "leipsoi": [0, 0, 0, 1, 2, 3, 2, 1, 3, 0, 0, 0],
  "lemnos": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "leros": [1, 1, 1, 2, 2, 3, 2, 1, 3, 2, 1, 1],
  "lesvos": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "mathraki": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "meganisi": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 0, 0],
  "milos": [0, 0, 1, 2, 3, 3, 1, 0, 3, 2, 1, 0],
  "mykonos": [0, 0, 0, 1, 2, 2, 3, 3, 3, 2, 0, 0],
  "naxos": [0, 0, 1, 2, 3, 3, 2, 1, 3, 2, 1, 0],
  "nisyros": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 0, 0],
  "oinousses": [0, 0, 1, 2, 2, 3, 2, 1, 3, 0, 0, 0],
  "othonoi": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "paros": [0, 0, 1, 2, 2, 3, 1, 1, 3, 2, 1, 0],
  "patmos": [0, 0, 1, 2, 3, 3, 1, 0, 3, 2, 1, 0],
  "paxos": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 0, 0],
  "poros": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 1],
  "psara": [0, 0, 0, 1, 2, 3, 2, 1, 3, 0, 0, 0],
  "pserimos": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "rethymno": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "rhodes": [2, 1, 2, 2, 2, 3, 2, 2, 3, 2, 2, 1],
  "salamis": [1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1],
  "samos": [1, 1, 2, 2, 3, 3, 1, 1, 3, 2, 2, 1],
  "samothrace": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 1, 0],
  "santorini": [0, 0, 1, 2, 2, 3, 0, 0, 3, 2, 1, 0],
  "schoinoussa": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "serifos": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 1, 0],
  "sifnos": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 1, 0],
  "sikinos": [0, 0, 0, 1, 2, 3, 1, 1, 3, 1, 0, 0],
  "skiathos": [0, 0, 1, 2, 2, 3, 2, 2, 3, 2, 1, 0],
  "skopelos": [0, 0, 1, 2, 2, 3, 1, 0, 3, 2, 1, 0],
  "skyros": [1, 2, 2, 2, 3, 3, 2, 1, 3, 2, 1, 1],
  "spetses": [1, 1, 2, 2, 3, 3, 1, 0, 3, 2, 2, 1],
  "symi": [0, 0, 1, 2, 3, 3, 1, 0, 3, 2, 2, 0],
  "syros": [1, 1, 2, 2, 3, 3, 2, 1, 3, 2, 2, 1],
  "telendos": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "thasos": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1],
  "therasia": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "thymaina": [0, 0, 0, 1, 2, 3, 2, 1, 3, 1, 0, 0],
  "tilos": [0, 0, 1, 2, 2, 3, 2, 1, 3, 2, 0, 0],
  "tinos": [0, 0, 1, 2, 3, 3, 2, 1, 3, 2, 1, 0],
  "zakynthos": [1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 2, 1]
};
