#!/usr/bin/env python3
"""Batch 3 verdicts: heavyweight pairs. Driven by Cloudflare path data (big-island
comparisons pull the most volume; Rhodes appears in 2 of the top 3 compare pages)
and GSC queries (kos-vs-rhodes 118i, corfu family 700i+ combined).

Inserts into vs_verdicts.json. Run build_compare_pages.py afterwards.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
V = ROOT / 'vs_verdicts.json'

BATCH = {
    'naxos__rhodes': {
        'en': "<p>These are both big, self-sufficient islands where a week fills itself — the choice is about what fills it. <strong>Rhodes (4.4)</strong> is history first: the medieval Old Town is the best walled city in Greece, Lindos is spectacular, and the resort machine along the east coast means flights, rooms and rental cars at every price. <strong>Naxos (4.5)</strong> is the better <em>Greek</em> holiday: the west-coast beach strip (Plaka, Mikri Vigla) beats anything on Rhodes, the mountain villages are living places rather than excursions, and food comes from the island itself — potatoes, graviera, citron.</p><p>Nightlife and access favour Rhodes (4.1 vs 3.5; direct international flights year-round). Beaches and affordability favour Naxos (4.8 vs 4.2, and noticeably cheaper). Families torn between them: Naxos, unless the kids are old enough to be bribed with a knights' castle.</p><p><strong>Verdict: Naxos for beaches and authenticity, Rhodes for history and a longer season.</strong></p>",
        'el': "<p>Δύο μεγάλα, αυτάρκη νησιά όπου η εβδομάδα γεμίζει μόνη της — το ερώτημα είναι με τι. Η <strong>Ρόδος (4.4)</strong> είναι πρώτα ιστορία: η μεσαιωνική Παλιά Πόλη είναι η καλύτερη οχυρωμένη πόλη της Ελλάδας, η Λίνδος εντυπωσιάζει, και η τουριστική μηχανή της ανατολικής ακτής σημαίνει πτήσεις, δωμάτια και αυτοκίνητα σε κάθε τιμή. Η <strong>Νάξος (4.5)</strong> είναι οι πιο <em>ελληνικές</em> διακοπές: η δυτική ακτή (Πλάκα, Μικρή Βίγλα) κερδίζει κάθε παραλία της Ρόδου, τα ορεινά χωριά είναι ζωντανοί τόποι κι όχι εκδρομές, και το φαγητό βγαίνει από το ίδιο το νησί — πατάτες, γραβιέρα, κίτρο.</p><p>Νυχτερινή ζωή και πρόσβαση γέρνουν προς Ρόδο (4.1 έναντι 3.5, απευθείας πτήσεις όλο τον χρόνο). Παραλίες και τιμές προς Νάξο (4.8 έναντι 4.2, και αισθητά φθηνότερα).</p><p><strong>Ετυμηγορία: Νάξος για παραλίες και αυθεντικότητα, Ρόδος για ιστορία και μεγαλύτερη σεζόν.</strong></p>",
    },
    'paros__rhodes': {
        'en': "<p>A Cyclades-versus-Dodecanese classic. <strong>Paros (4.1)</strong> is the polished Cycladic all-rounder: perfect beaches (5.0), Naoussa's harbour nightlife (5.0), whitewashed lanes — and prices to match (affordability 2.2). <strong>Rhodes (4.4)</strong> is three islands in one: a UNESCO medieval city, a resort coast, and an interior most visitors never see, at prices a notch friendlier (3.5).</p><p>Choose by trip length and season. For 4–5 days of beach-and-town in high summer, Paros is tighter and prettier. For a full week — especially early or late season, when Paros empties but Rhodes keeps flying — Rhodes gives you more to do on the inevitable windy day: Lindos, Kamiros, the butterfly valley, Symi as a day trip. Paros needs no car (3.0); Rhodes without one (5.0) shrinks to a resort.</p><p><strong>Verdict: Paros for the postcard week, Rhodes for the varied one — and for anyone travelling outside July–August.</strong></p>",
        'el': "<p>Κλασικό δίλημμα Κυκλάδες-Δωδεκάνησα. Η <strong>Πάρος (4.1)</strong> είναι το γυαλισμένο κυκλαδίτικο all-rounder: τέλειες παραλίες (5.0), η νυχτερινή Νάουσα (5.0), ασβεστωμένα σοκάκια — και τιμές αντίστοιχες (οικονομικά 2.2). Η <strong>Ρόδος (4.4)</strong> είναι τρία νησιά σε ένα: μεσαιωνική πόλη UNESCO, ακτή θερέτρων, και μια ενδοχώρα που οι περισσότεροι δεν βλέπουν ποτέ, σε τιμές λίγο φιλικότερες (3.5).</p><p>Διάλεξε με βάση διάρκεια και εποχή. Για 4–5 μέρες παραλία-και-χώρα μέσα στο κατακαλόκαιρο, η Πάρος είναι πιο συμπαγής και όμορφη. Για ολόκληρη εβδομάδα — ειδικά αρχές ή τέλη σεζόν, όταν η Πάρος αδειάζει αλλά η Ρόδος συνεχίζει — η Ρόδος έχει περισσότερα για τη μέρα με τον αέρα: Λίνδος, Κάμιρος, Πεταλούδες, Σύμη ημερήσια. Η Πάρος δεν θέλει αυτοκίνητο (3.0)· η Ρόδος χωρίς αυτοκίνητο (5.0) γίνεται απλώς θέρετρο.</p><p><strong>Ετυμηγορία: Πάρος για την καρτ-ποστάλ εβδομάδα, Ρόδος για την ποικιλία — και για όποιον ταξιδεύει εκτός Ιουλίου–Αυγούστου.</strong></p>",
    },
    'corfu__heraklion': {
        'en': "<p>Green Ionian elegance against Crete's busiest region — and honestly, two different countries' worth of holiday. <strong>Corfu (4.2)</strong> is Venetian: an elegant UNESCO old town, olive-covered hills falling into blue coves, kumquat liqueur and Italianate food. <strong>Heraklion (4.2)</strong> is the gateway to Minoan civilisation — Knossos and the archaeological museum are world-class — plus the wine country of Peza and a nightlife scene (4.7) that runs all year because real people live there.</p><p>Beaches favour Corfu marginally (3.9 vs 3.5) — but neither is the beach champion of its own island group. Access is a wash: both fly direct from most of Europe. The honest tiebreaker is atmosphere: Corfu feels like a holiday, Heraklion feels like Greece with a holiday attached. Families and first-timers: Corfu. Archaeology, food and city energy: Heraklion — and rent the car (5.0), the region only opens up if you drive.</p><p><strong>Verdict: Corfu for charm, Heraklion for depth.</strong></p>",
        'el': "<p>Η πράσινη κομψότητα του Ιονίου απέναντι στην πιο πολύβουη γωνιά της Κρήτης — ειλικρινά, διακοπές δύο διαφορετικών χωρών. Η <strong>Κέρκυρα (4.2)</strong> είναι βενετσιάνικη: κομψή παλιά πόλη UNESCO, ελαιώνες που πέφτουν σε μπλε όρμους, κουμκουάτ και ιταλίζουσα κουζίνα. Το <strong>Ηράκλειο (4.2)</strong> είναι η πύλη του μινωικού πολιτισμού — Κνωσός και Αρχαιολογικό Μουσείο παγκόσμιας κλάσης — συν τα κρασιά της Πεζών και νυχτερινή ζωή (4.7) που κρατά όλο τον χρόνο, γιατί εκεί ζει αληθινός κόσμος.</p><p>Στις παραλίες προηγείται οριακά η Κέρκυρα (3.9 έναντι 3.5) — αλλά καμία δεν είναι η πρωταθλήτρια της περιοχής της. Η πρόσβαση ισοπαλία: απευθείας πτήσεις και οι δύο. Το πραγματικό κριτήριο είναι η ατμόσφαιρα: η Κέρκυρα μοιάζει με διακοπές, το Ηράκλειο με Ελλάδα που έχει και διακοπές. Οικογένειες και πρωτάρηδες: Κέρκυρα. Αρχαιολογία, φαγητό, ενέργεια πόλης: Ηράκλειο — και νοίκιασε αυτοκίνητο (5.0).</p><p><strong>Ετυμηγορία: Κέρκυρα για γοητεία, Ηράκλειο για βάθος.</strong></p>",
    },
    'corfu__santorini': {
        'en': "<p>The two most photographed islands in Greece, photographing completely different things. <strong>Santorini (4.8)</strong> is the caldera: a geological drama with wine and architecture on top, unbeatable for 2–3 days, brutally expensive (affordability 1.0) and not really a beach island (3.2). <strong>Corfu (4.2)</strong> is a green, lived-in island with an aristocratic old town, forested hills, and enough coastline variety for two weeks — at three-fifths the price (3.2).</p><p>The honest framing: Santorini is an experience, Corfu is a holiday. Honeymoon or once-in-a-lifetime trip with money set aside — Santorini, and stay somewhere with the view because the view is the product. Family week, mixed group, or any trip where the budget matters — Corfu, no contest. Combining them doesn't work; they're on opposite sides of the country with no direct link.</p><p><strong>Verdict: Santorini for the spectacle, Corfu for the stay.</strong></p>",
        'el': "<p>Τα δύο πιο φωτογραφημένα νησιά της Ελλάδας — που φωτογραφίζουν εντελώς διαφορετικά πράγματα. Η <strong>Σαντορίνη (4.8)</strong> είναι η καλντέρα: ένα γεωλογικό δράμα με κρασί και αρχιτεκτονική από πάνω, ασυναγώνιστη για 2–3 μέρες, βάναυσα ακριβή (οικονομικά 1.0) και όχι πραγματικά νησί παραλιών (3.2). Η <strong>Κέρκυρα (4.2)</strong) είναι πράσινο, κατοικημένο νησί με αρχοντική παλιά πόλη, δασωμένους λόφους και ακτογραμμή για δύο εβδομάδες — στα τρία πέμπτα της τιμής (3.2).</p><p>Η ειλικρινής διατύπωση: η Σαντορίνη είναι εμπειρία, η Κέρκυρα είναι διακοπές. Μήνας του μέλιτος ή ταξίδι-ζωής με ανάλογο μπάτζετ — Σαντορίνη, και μείνε με θέα, γιατί η θέα είναι το προϊόν. Οικογενειακή εβδομάδα ή οποιοδήποτε ταξίδι όπου μετράει το πορτοφόλι — Κέρκυρα, χωρίς δεύτερη σκέψη. Συνδυασμός δεν γίνεται· άλλη άκρη της χώρας, καμία απευθείας σύνδεση.</p><p><strong>Ετυμηγορία: Σαντορίνη για το θέαμα, Κέρκυρα για τη διαμονή.</strong></p>",
    },
    'heraklion__santorini': {
        'en': "<p>Neighbours with a daily ferry, so this is also a 'both?' question. <strong>Santorini (4.8)</strong> you know: the caldera, the sunsets, the prices (1.0). <strong>Heraklion (4.2)</strong> is the anti-Santorini: a working Cretan city with Knossos and a world-class museum, wine villages, and food that locals actually eat, at double the affordability (3.5).</p><p>As a straight choice: 2–3 days and a camera — Santorini; a week and an appetite — Heraklion, with a car (5.0). But the smart play is the combination: fly into one, out of the other, with the 2-hour ferry between them. Three nights of caldera spectacle, four of Cretan substance — it fixes both islands' weaknesses, and our Budget page prices the whole route.</p><p><strong>Verdict: Santorini for the show, Heraklion for the meal — ideally in that order, connected by ferry.</strong></p>",
        'el': "<p>Γείτονες με καθημερινό πλοίο — άρα το ερώτημα είναι και «μήπως και τα δύο;». Τη <strong>Σαντορίνη (4.8)</strong> την ξέρεις: καλντέρα, ηλιοβασιλέματα, τιμές (1.0). Το <strong>Ηράκλειο (4.2)</strong> είναι η αντι-Σαντορίνη: εργαζόμενη κρητική πόλη με Κνωσό και κορυφαίο μουσείο, χωριά του κρασιού, και φαγητό που τρώνε πραγματικά οι ντόπιοι, με διπλάσια προσιτότητα (3.5).</p><p>Ως ξερή επιλογή: 2–3 μέρες και φωτογραφική — Σαντορίνη· μια εβδομάδα και όρεξη — Ηράκλειο, με αυτοκίνητο (5.0). Αλλά η έξυπνη κίνηση είναι ο συνδυασμός: πτήση μέσα από το ένα, έξω από το άλλο, με το 2ωρο πλοίο ανάμεσα. Τρεις νύχτες θέαμα καλντέρας, τέσσερις κρητική ουσία — διορθώνει τις αδυναμίες και των δύο, και το Μπάτζετ μας κοστολογεί όλη τη διαδρομή.</p><p><strong>Ετυμηγορία: Σαντορίνη για την παράσταση, Ηράκλειο για το τραπέζι — ιδανικά με αυτή τη σειρά, με πλοίο ανάμεσα.</strong></p>",
    },
    'chania__rhodes': {
        'en': "<p>The two best 'old town plus everything' islands in Greece, a genuine tie on our board (Chania 4.8, Rhodes 4.4) that breaks on specifics. <strong>Chania</strong> has the better beaches by a distance — Balos, Elafonisi, Falassarna are a 5.0 for a reason — plus the White Mountains, the Samaria gorge, and a harbour town that's beautiful without being a museum. <strong>Rhodes</strong> has the greater monument: the walled medieval city is the real thing, lived-in and vast, and its season runs longer with cheaper package infrastructure.</p><p>Both demand a car (5.0). Nightlife is a wash. History: Rhodes for the middle ages, Chania for everything from Minoans to World War II. If your trip is built around swimming, Chania wins outright; if it's built around wandering stone streets at dusk, Rhodes edges it.</p><p><strong>Verdict: Chania, narrowly — the beach gap matters more often than the castle gap. Rhodes if you travel in May or October.</strong></p>",
        'el': "<p>Τα δύο καλύτερα νησιά «παλιά πόλη συν τα πάντα» της Ελλάδας — ουσιαστική ισοπαλία στον πίνακά μας (Χανιά 4.8, Ρόδος 4.4) που κρίνεται στις λεπτομέρειες. Τα <strong>Χανιά</strong> έχουν τις καλύτερες παραλίες με διαφορά — Μπάλος, Ελαφονήσι, Φαλάσαρνα δεν παίρνουν 5.0 τυχαία — συν Λευκά Όρη, Σαμαριά, και ένα λιμάνι όμορφο χωρίς να είναι μουσείο. Η <strong>Ρόδος</strong> έχει το μεγαλύτερο μνημείο: η μεσαιωνική πόλη είναι αληθινή, κατοικημένη και απέραντη, και η σεζόν της κρατά περισσότερο με φθηνότερη υποδομή.</p><p>Και τα δύο απαιτούν αυτοκίνητο (5.0). Νυχτερινή ζωή ισοπαλία. Ιστορία: Ρόδος για Μεσαίωνα, Χανιά για όλα — από Μινωίτες μέχρι Β' Παγκόσμιο. Αν το ταξίδι σου χτίζεται γύρω από το κολύμπι, τα Χανιά κερδίζουν καθαρά· αν γύρω από πέτρινα σοκάκια το σούρουπο, η Ρόδος προηγείται.</p><p><strong>Ετυμηγορία: Χανιά, οριακά — το χάσμα στις παραλίες μετράει πιο συχνά από το χάσμα στα κάστρα. Ρόδος αν ταξιδεύεις Μάιο ή Οκτώβριο.</strong></p>",
    },
    'kos__santorini': {
        'en': "<p>These attract the same charter flights and completely different travellers. <strong>Kos (3.7)</strong> is the easy Dodecanese package: flat, cyclable, long sandy beaches (4.0), Hippocrates' Asklepieion for a culture morning, and honest prices (3.8). <strong>Santorini (4.8)</strong> is the world-famous one — caldera, wine, architecture — at world-famous prices (1.0) and with beaches that are volcanic curiosities rather than swimming destinations (3.2).</p><p>The decision is almost financial. A week on Kos costs roughly what three nights on Santorini do, hotel for hotel. If this is the year's one big trip and the caldera photo is the dream, take Santorini and don't look at receipts. If you want two easy weeks of sun with kids or a bike, Kos delivers exactly that — and you can day-trip to Nisyros' volcano for your geological drama at a fraction of the cost.</p><p><strong>Verdict: Santorini for the bucket list, Kos for the actual holiday.</strong></p>",
        'el': "<p>Τραβούν τα ίδια charter και εντελώς διαφορετικούς ταξιδιώτες. Η <strong>Κως (3.7)</strong> είναι το εύκολο δωδεκανησιακό πακέτο: επίπεδη, ποδηλατική, μεγάλες αμμουδιές (4.0), το Ασκληπιείο για ένα πρωινό πολιτισμού, και τίμιες τιμές (3.8). Η <strong>Σαντορίνη (4.8)</strong> είναι η παγκοσμίως διάσημη — καλντέρα, κρασί, αρχιτεκτονική — σε παγκοσμίως διάσημες τιμές (1.0) και με παραλίες που είναι ηφαιστειακά αξιοπερίεργα, όχι προορισμοί κολύμβησης (3.2).</p><p>Η απόφαση είναι σχεδόν οικονομική. Μια εβδομάδα στην Κω κοστίζει περίπου όσο τρεις νύχτες στη Σαντορίνη. Αν είναι το μεγάλο ταξίδι της χρονιάς και η φωτογραφία της καλντέρας είναι το όνειρο, πάρε Σαντορίνη και μην κοιτάς αποδείξεις. Αν θες δύο άνετες εβδομάδες ήλιου με παιδιά ή ποδήλατο, η Κως τα δίνει ακριβώς — με ημερήσια στο ηφαίστειο της Νισύρου για το γεωλογικό σου δράμα, σε κλάσμα της τιμής.</p><p><strong>Ετυμηγορία: Σαντορίνη για το bucket list, Κως για τις πραγματικές διακοπές.</strong></p>",
    },
    'kos__mykonos': {
        'en': "<p>Both party-capable, both airport islands, wildly different bills. <strong>Mykonos (4.3)</strong> is the international scene: 5.0 nightlife, celebrity beach clubs, Delos next door for the best archaeological day trip in the Aegean — and affordability of 1.0, which is not a typo. <strong>Kos (3.7)</strong> parties too — the bar street in Kos Town is infamous — but it's a package island at package prices (3.8), with better swimming than it gets credit for.</p><p>If nightlife means table service and DJs you've heard of, Mykonos is simply the product, and you budget accordingly — our Budget page will be blunt with you. If nightlife means bars, beach days and not checking the account on Wednesday, Kos wins on points. There is no shame version of this choice: they're both doing exactly what they advertise.</p><p><strong>Verdict: Mykonos for the scene, Kos for the season — decide with your bank app open.</strong></p>",
        'el': "<p>Και τα δύο ξέρουν από πάρτι, και τα δύο έχουν αεροδρόμιο, εντελώς διαφορετικοί λογαριασμοί. Η <strong>Μύκονος (4.3)</strong> είναι η διεθνής σκηνή: νυχτερινή ζωή 5.0, beach clubs με διασημότητες, η Δήλος δίπλα για την καλύτερη αρχαιολογική ημερήσια του Αιγαίου — και οικονομικά 1.0, που δεν είναι τυπογραφικό. Η <strong>Κως (3.7)</strong> ξέρει κι αυτή από πάρτι — ο δρόμος με τα μπαρ είναι διαβόητος — αλλά είναι νησί πακέτου σε τιμές πακέτου (3.8), με καλύτερο κολύμπι απ' όσο της αναγνωρίζουν.</p><p>Αν νυχτερινή ζωή σημαίνει table service και DJs που ξέρεις με το όνομα, η Μύκονος είναι απλώς το προϊόν, και προϋπολογίζεις ανάλογα — το Μπάτζετ μας θα είναι ωμό μαζί σου. Αν σημαίνει μπαρ, μέρες παραλίας και να μην κοιτάς τον λογαριασμό την Τετάρτη, η Κως κερδίζει στα σημεία.</p><p><strong>Ετυμηγορία: Μύκονος για τη σκηνή, Κως για τη σεζόν — αποφάσισε με το banking app ανοιχτό.</strong></p>",
    },
    'chania__heraklion': {
        'en': "<p>The real Crete question — most visitors pick a base and stay west or east of it. <strong>Chania (4.8)</strong> is the postcard half: the Venetian harbour, Balos and Elafonisi (beaches 5.0), the gorges. <strong>Heraklion (4.2)</strong> is the substance half: Knossos, the great museum, the wine country, city nightlife (4.7) that doesn't close in October.</p><p>For a first trip focused on swimming and scenery, Chania and it isn't close. For archaeology, food and a base that works off-season, Heraklion. But here's the honest structural answer: Crete is enormous, and the Chania–Heraklion drive is under two hours on the highway. A week split 4–3 — fly into Chania, out of Heraklion — beats either alone, and skips the backtrack. Both halves demand a car (5.0); budget for it from day one.</p><p><strong>Verdict: Chania if you must choose; a split week if you're wise.</strong></p>",
        'el': "<p>Το πραγματικό κρητικό δίλημμα — οι περισσότεροι διαλέγουν βάση και μένουν δυτικά ή ανατολικά της. Τα <strong>Χανιά (4.8)</strong> είναι το μισό της καρτ-ποστάλ: βενετσιάνικο λιμάνι, Μπάλος και Ελαφονήσι (παραλίες 5.0), φαράγγια. Το <strong>Ηράκλειο (4.2)</strong> είναι το μισό της ουσίας: Κνωσός, το μεγάλο μουσείο, τα κρασοχώρια, νυχτερινή ζωή πόλης (4.7) που δεν κλείνει τον Οκτώβριο.</p><p>Για πρώτο ταξίδι με επίκεντρο κολύμπι και τοπία, Χανιά — και δεν είναι καν κοντινό. Για αρχαιολογία, φαγητό και βάση που δουλεύει εκτός σεζόν, Ηράκλειο. Αλλά η ειλικρινής δομική απάντηση: η Κρήτη είναι τεράστια, και η διαδρομή Χανιά–Ηράκλειο κάτω από δύο ώρες στον ΒΟΑΚ. Εβδομάδα μοιρασμένη 4–3 — πτήση μέσα από Χανιά, έξω από Ηράκλειο — κερδίζει οποιοδήποτε από τα δύο μόνο του. Και τα δύο απαιτούν αυτοκίνητο (5.0)· βάλ' το στο μπάτζετ από την πρώτη μέρα.</p><p><strong>Ετυμηγορία: Χανιά αν πρέπει να διαλέξεις· μοιρασμένη εβδομάδα αν είσαι σοφός.</strong></p>",
    },
    'rhodes__zakynthos': {
        'en': "<p>Two package heavyweights on opposite sides of Greece. <strong>Zakynthos (4.1)</strong> is the beach specialist: Navagio's shipwreck cove, turtle bays, and the Ionian's soft green light — beaches 4.8, history 2.5, and that ratio tells you the whole island. <strong>Rhodes (4.4)</strong> is the generalist: real medieval history (5.0), a longer season, better ferry connections onward (Symi, Halki), and more to do when the wind blows.</p><p>For a one-week beach holiday, especially a young group or a couple chasing swimming spots, Zakynthos delivers more per day. For anything longer, anything off-peak, or any traveller who gets restless on a sunbed by day three, Rhodes has the deeper reserves. Both need a car; Zakynthos' famous spots crowd brutally by 11am in August — go at opening time or by boat.</p><p><strong>Verdict: Zakynthos for the perfect beach week, Rhodes for everything beyond it.</strong></p>",
        'el': "<p>Δύο βαριά χαρτιά του οργανωμένου τουρισμού σε αντίθετες άκρες της Ελλάδας. Η <strong>Ζάκυνθος (4.1)</strong> είναι η σπεσιαλίστα των παραλιών: το Ναυάγιο, οι κόλποι με τις χελώνες, το απαλό πράσινο φως του Ιονίου — παραλίες 4.8, ιστορία 2.5, κι αυτή η αναλογία σού λέει όλο το νησί. Η <strong>Ρόδος (4.4)</strong> είναι η γενικίστρια: αληθινή μεσαιωνική ιστορία (5.0), μεγαλύτερη σεζόν, καλύτερες ακτοπλοϊκές συνέχειες (Σύμη, Χάλκη), και περισσότερα να κάνεις όταν φυσάει.</p><p>Για μία εβδομάδα καθαρά παραλίας — ειδικά νεανική παρέα ή ζευγάρι που κυνηγά κολύμπια — η Ζάκυνθος αποδίδει περισσότερα τη μέρα. Για οτιδήποτε μεγαλύτερο, εκτός αιχμής, ή για ταξιδιώτη που βαριέται στην ξαπλώστρα από την τρίτη μέρα, η Ρόδος έχει τα βαθύτερα αποθέματα. Και οι δύο θέλουν αυτοκίνητο· τα διάσημα σημεία της Ζακύνθου ασφυκτιούν από τις 11 τον Αύγουστο — πήγαινε με το άνοιγμα ή με σκάφος.</p><p><strong>Ετυμηγορία: Ζάκυνθος για την τέλεια εβδομάδα παραλίας, Ρόδος για όλα τα υπόλοιπα.</strong></p>",
    },
}


def main():
    v = json.loads(V.read_text(encoding='utf-8'))
    added = 0
    for k, entry in BATCH.items():
        a, b = k.split('__')
        assert k == '__'.join(sorted([a, b])), f'key not sorted: {k}'
        if k in v:
            print(f'  skip (exists): {k}')
            continue
        v[k] = entry
        added += 1
    V.write_text(json.dumps(v, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'✓ {added} verdicts added ({len(v)} total pairs)')


if __name__ == '__main__':
    main()
