#!/usr/bin/env python3
"""Market data loader — the one place build tools read destination data from.

A "market" is one country/region site built on the shared engine
(markets/greece, later markets/croatia ...). Its hand-edited sources live in
markets/<market>/*.json; this module reads them and generates market-data.js,
the browser copy that every page loads before i18n.js and script.js.

Pick the market with the MARKET environment variable (default: greece).
Edit the JSON, never market-data.js.
"""
import hashlib
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKET = os.environ.get('MARKET', 'greece')
MDIR = ROOT / 'markets' / MARKET
JS_OUT = ROOT / 'market-data.js'

_cache = {}


def _load(name):
    if name not in _cache:
        _cache[name] = json.loads((MDIR / name).read_text(encoding='utf-8'))
    return _cache[name]


def destinations():
    """key -> fields (name, lat, lng, beach, hist, night, access, afford, car_need,
    total, area, pop, days, island_group, has_airport, flags ...). Insertion
    order is the site's default order."""
    return _load('destinations.json')


def clusters():
    return _load('clusters.json')


def home():
    """{"featured": [{key, tagEn, tagEl}], "hero_keys": [...]}"""
    return _load('home.json')


def cluster_of():
    out = {}
    for ck, c in clusters().items():
        for k in c.get('members', []):
            out[k] = ck
    return out


def wtv_tags():
    """Month tags (avoid 0 · ok 1 · great 2 · perfect 3) from each destination's
    when_to_visit.months — the JSON with per-month reasons is the authored source."""
    tagv = {'avoid': 0, 'ok': 1, 'great': 2, 'perfect': 3}
    out = {}
    for f in sorted((ROOT / 'islands').glob('*.json')):
        try:
            j = json.loads(f.read_text(encoding='utf-8'))
        except Exception:
            continue
        months = (j.get('when_to_visit') or {}).get('months') or [] if isinstance(j, dict) else []
        if len(months) != 12:
            continue
        out[f.stem] = [tagv.get(str(m.get('tag', '')).lower(), 1) for m in months]
    return out


# ── Languages ──────────────────────────────────────────────────────────────
# markets/<market>/market.json -> "languages": [{code, label, name, prefix, default}].
# Build tools loop over langs(); per-language values are passed as {code: value}
# dicts and anything for a language the market doesn't have is simply dropped.

def config():
    return _load('market.json')


def languages():
    return config()['languages']


def langs():
    return [l['code'] for l in languages()]


def default_lang():
    return next((l['code'] for l in languages() if l.get('default')), langs()[0])


def has_lang(code):
    return code in langs()


def lang_prefix(code):
    return next((l.get('prefix', '') for l in languages() if l['code'] == code), '')



def feature(name):
    """Is an optional page family on for this market? (market.json "features"; missing = on)"""
    return bool(config().get('features', {}).get(name, True))


def per_lang(values):
    """{code: value} -> [value, ...] for the market's languages, in config order."""
    return [values[c] for c in langs() if c in values]


def hreflang(urls, kind='link', sep='\n', indent=''):
    """Alternate-language tags for one page: urls = {code: absolute url}.
    kind 'link' -> <link ...> for <head>, 'xhtml' -> <xhtml:link .../> for sitemaps.
    Empty for a single-language market (hreflang only matters with alternates)."""
    have = [c for c in langs() if c in urls]
    if len(have) < 2:
        return ''
    pairs = [(c, urls[c]) for c in have] + [('x-default', urls[default_lang()])]
    fmt = ('<link rel="alternate" hreflang="{}" href="{}">' if kind == 'link'
           else '<xhtml:link rel="alternate" hreflang="{}" href="{}"/>')
    return sep.join(indent + fmt.format(c, u) for c, u in pairs)


def _obj_lines(d, indent='  '):
    """One entry per line so diffs stay readable."""
    rows = [f'{indent}{json.dumps(k, ensure_ascii=False)}: {json.dumps(v, ensure_ascii=False)}'
            for k, v in d.items()]
    return '{\n' + ',\n'.join(rows) + '\n}'


def render_js():
    h = home()
    return (
        '/* GENERATED by tools/market.py from markets/' + MARKET + '/*.json and islands/*.json.\n'
        '   Edit the JSON and rebuild; changes made here are overwritten. */\n'
        f'const MARKET_KEY = {json.dumps(MARKET)};\n'
        f'const MARKET_LANGS = {json.dumps(languages(), ensure_ascii=False)};\n'
        f'const MARKET_FEATURES = {json.dumps(config().get("features", {}))};\n'
        f'const ISLANDS_DATA = {_obj_lines(destinations())};\n'
        f'const ISLAND_CLUSTERS = {json.dumps(clusters(), ensure_ascii=False, indent=2)};\n'
        f'const HOMEPAGE_FEATURED = {json.dumps(h["featured"], ensure_ascii=False, indent=2)};\n'
        f'const HOME_HERO_KEYS = {json.dumps(h["hero_keys"], ensure_ascii=False)};\n'
        f'const WTV_TAGS = {_obj_lines(wtv_tags())};\n'
    )


def version():
    """Short content hash used as the ?v= cache-buster."""
    return hashlib.md5(JS_OUT.read_bytes()).hexdigest()[:8] if JS_OUT.exists() else '0'


def sync_theme():
    """Copy markets/<market>/theme.css into style.css between the THEME markers."""
    src = MDIR / 'theme.css'
    if not src.exists():
        return
    css = ROOT / 'style.css'
    s = css.read_text(encoding='utf-8')
    a, b = s.index('/* THEME:BEGIN'), s.index('/* THEME:END */')
    a = s.index('\n', a) + 1
    new = s[:a] + src.read_text(encoding='utf-8') + s[b:]
    if new != s:
        css.write_text(new, encoding='utf-8')
        print(f'✓ style.css theme block synced from markets/{MARKET}/theme.css — bump style.css?v=')


def write_js():
    """Write market-data.js (only if changed) and point index.html at the new version."""
    sync_theme()
    js = render_js()
    old = JS_OUT.read_text(encoding='utf-8') if JS_OUT.exists() else None
    if js != old:
        JS_OUT.write_text(js, encoding='utf-8')
        print(f'✓ market-data.js written ({len(destinations())} destinations, market={MARKET})')
    v = version()
    for idx in (ROOT / 'index.html', ROOT / 'el' / 'index.html'):   # hand-maintained homepages
        src = idx.read_text(encoding='utf-8')
        new = re.sub(r'market-data\.js\?v=[0-9a-z]+', f'market-data.js?v={v}', src)
        if new != src:
            idx.write_text(new, encoding='utf-8')
    return v


if __name__ == '__main__':
    print('market-data.js version', write_js())
